version: 2.1

orbs:
  code-quality: promoboxx/code-quality@0.0.11
  testing: promoboxx/testing@0.0.13

jobs:
  build:
    docker:
      - image: pbxx/go-docker-base:master-latest
        auth:
          username: $DOCKER_LOGIN
          password: $DOCKER_PASSWORD
    working_directory: /go/src/github.com/promoboxx/migrate
    steps:
      - checkout
      - run:
          name: build go-migrate
          command: |
            go build -mod vendor main.go
  build_and_push:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login to DockerHub
          command: docker login -u "$DOCKER_LOGIN" -p "$DOCKER_PASSWORD"
      - run:
          name: Create and use buildx builder
          command: |
            docker buildx create --name multiarch --use
            docker buildx inspect --bootstrap
      - run:
          name: Build and push multi-arch image
          command: |
            docker buildx build \
              --platform linux/amd64,linux/arm64 \
              --tag pbxx/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1} \
              --tag pbxx/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BRANCH}-latest \
              --push \
              .
workflows:
  version: 2.1
  build_and_publish_docker_image:
    jobs:
      - build:
          context: "dockerhub"
      - build_and_push:
          context: "dockerhub"
          requires:
            - build
            - testing/test
     
